name: full_picker_example
description: A Flutter project for full picker example.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  full_picker_plus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true